config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/importation.rb
class Importation < ApplicationRecord
  has_many :products

  enum status: %i[pending processing complete]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :importation
  has_many :variants, inverse_of: :product

  accepts_nested_attributes_for :variants

  validates :name, :description, presence: true

  before_validation :check_invalid_variants
  
  private
  def check_invalid_variants
    return if variants.all?(&:valid?)
    return if variants.all?(&:invalid?)

    self.variants = variants.select(&:valid?)
  end
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product, inverse_of: :variants

  validates :name, :price, :product, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < InheritedResources::Base
  before_action :get_totals, only: %i[index]
  def index
    @importations = Importation.all
  end

  private
  def get_totals
    @created_products = Importation.sum(:total_success)
    @rejected_products = Importation.sum(:total_error)
    @requested_products = Importation.sum(:total_products)
  end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  skip_before_action :verify_authenticity_token
  
  def index
    @products = Product.all
    respond_to do |f|
      f.html
      f.json { render json: @products }
    end
  end

  def create
    products = permitted_params[:products]
    importation = Importation.create
    ProductsImportationJob.perform_later(products.take(10000), importation.id)
    message = 'The importation request is being processed.'
    message = 'The importation request is being processed. Since the request is greater than 10,000 products, the first 10,000 will be taken.' if products.length > 10000
    respond_to do |f|
      f.html
      f.json {
        render json: {
          message: message
        }
      }
    end
  end
  
  private
  def permitted_params
    fields = %i[name description]
    fields.push(variants_attributes: %i[name price])
    params.permit(products: fields)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.erb
<div style="padding: 1rem;">
  <div style="display: flex; align-content: center; justify-content: center; padding-bottom: .5rem; width: 100%">
    <h1>
      Dashboard
    </h1>
  </div>
  
  <div style="display: grid; grid-template-columns: auto auto auto; grid-gap: 2rem; height: 10rem; padding-bottom: 1rem">
    <div style="grid-column: 1 / span 1; text-align: center; height: 100%; box-shadow: 0rem 0rem .7rem #2A2E32">
      <h3>
        Requested Products
      </h3>
      <h3>
        <%= @requested_products %>
      </h3>
    </div>
    <div style="grid-column: 2 / span 1; text-align: center; height: 100%; box-shadow: 0rem 0rem .7rem #2A2E32">
      <h3>
        Loaded Products
      </h3>
      <h3>
        <%= @created_products %>
      </h3>
    </div>
    <div style="grid-column: 3 / span 1; text-align: center; height: 100%; box-shadow: 0rem 0rem .7rem #2A2E32">
      <h3>
        Rejected Products
      </h3>
      <h3>
        <%= @rejected_products %>
      </h3>
    </div>
  </div>
  
  <div style="display: grid; grid-template-columns: auto; grid-gap: 2rem; height: 10rem;">
    <div style="grid-column: 1 / span 1; text-align: center; height: 100%; box-shadow: 0rem 0rem .7rem #2A2E32; padding-bottom: 1rem">
      <h3>
        Importation Status
      </h3>
      <div style="display: grid; grid-template-columns: auto auto auto auto auto; grid-gap: 2rem;">
        <% @importations.each do |i| %>
          <div style="grid-column: 1 / span 1; text-align: center; height: 100%;">
            <b>
              Id
            </b>
            <%= i.id %>
          </div>
          <div style="grid-column: 2 / span 1; text-align: center; height: 100%;">
            <b>
              Total Products
            </b>
            <%= i.total_products %>
          </div>
          <div style="grid-column: 3 / span 1; text-align: center; height: 100%;">
            <b>
              Total Success
            </b>
            <%= i.total_success %>
          </div>
          <div style="grid-column: 4 / span 1; text-align: center; height: 100%;">
            <b>
              Total Error
            </b>
            <%= i.total_error %>
          </div>
          <div style="grid-column: 5 / span 1; text-align: center; height: 100%;">
            <b>
              Status
            </b>
            <%= i.status %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce Vive Tech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.erb
<div style="padding: 1rem;">
  <div style="display: flex; align-content: center; justify-content: center; padding-bottom: .5rem; width: 100%">
    <div style="width: 100%">
      <span>
        <%= link_to 'Back', root_path %>
      </span>
      <h1 style="text-align: center">
        Products
      </h1>
    </div>
  </div>
  
  <div style="display: flex; justify-content: center; text-align: center; padding-top: .5rem">
    <table style="width: 90%;">
      <thead>
        <tr>
          <th>
            Name
          </th>
          <th>
            Description
          </th>
          <th>
            Actions
          </th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |p| %>
          <tr>
            <td>
              <%= p.name %>
            </td>
            <td>
              <%= p.description %>
            </td>
            <td>
              <%= link_to 'details', p %>
            </td>
          <tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/show.erb
<div style="padding: 1rem">
  <div style="display: flex; align-content: center; justify-content: center; padding-bottom: .5rem; width: 100%">
    <div style="width: 100%">
      <span>
        <%= link_to 'Back', products_path %>
      </span>
      <h1 style="text-align: center">
        <%= @product.name %>
      </h1>
    </div>
  </div>

  <div style="display: flex; justify-content: center; text-align: justify; padding-top: .5rem; padding-bottom: .5rem">
    <p>
      <%= @product.description %>
    </p>
  </div>

  <div style="display: flex; justify-content: center; text-align: center; padding-top: .5rem">
    <table style="width: 90%;">
      <thead>
        <tr>
          <th>
            Name
          </th>
          <th>
            Description
          </th>
        </tr>
      </thead>
      <tbody>
        <% @product.variants.each do |v| %>
          <tr>
            <td>
              <%= v.name %>
            </td>
            <td>
              <%= v.price %>
            </td>
          <tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>